# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('designer', models.CharField(max_length=200)),
                ('note', models.TextField()),
            ],
        ),
    ]
