# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinscene', '0002_auto_20171117_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(default='blank'),
        ),
    ]
