# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinscene', '0003_location_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
